import nuke, nukescripts

notes = [
	"We want it dark and glowy",
	"Make it invisible, but we want to see it",
	"There is nothing wrong here",
	"Make it look pretty",
	"It feels wrong, fix it",
	"Too Magenta",
	"Approved",
	"let's try something different",
	"Can we have few versions of this",
	"Let's go back to version 1",
	"Final",
	"It should be easy, No?"
	"More Rain",
	"Let's massage it",
	"Just one small note",
	"Can we have it by tomorrow",
	"That grass at the corner, feels too distracting",
	"Add some lensflare, I think it will be nice",
	"Let's make more realistic....but not too much, you know",
	"Can you match this...and that...and that one also",
	"Visor reflection too yellow",
	"Visor reflection not yellow enough",
	"Pick somewhere in between",
	"Too Pink, too Salmon",
	"Something's wrong, I don't know what",
	"What do you think",
	"It looks great, but..................",
	"Could use more glow",
	"Make explosion bigger",
	"ok",
	"next",
	".",
	"Could be better",
	"We’ll check to see whether MPC can supply an updated render for this",
	"Warmer",
	"Cooler",
	"You diserve a kiss",
	"it needs more shape",
	"Fucking love this",
	]
